
# Main Directories
local_directory: "Data"
online_directory: "https://s3.ir-tbz-sh1.arvanstorage.ir/sdac/ihbs"

# Years
default_first_year: 1363
default_last_year: 1400

# Folder Names
original_folder_name: '1_original_files'
raw_data_folder_name: '2_raw_data'
csv_folder_name: '3_csv_files'
parquet_folder_name: '4_parquets'

# Storage Method
# can be csv or sql
storage_technology: csv

# Map
default_map: humandata
